app:
  domain: https://wanted-talented-peacock.ngrok-free.app
  auth:
    jwt:
      secret: ${AUTH_SERVICE_TOKEN_SECRET:qrestor_secret}
  minio:
    server:
      url: ${MIN_IO_HOST:https://127.0.0.1:9000}
      access-key: ${MIN_IO_ACCESS_KEY:qrestor123}
      secret-key: ${MIN_IO_SECRET_KEY:qrestor123}
spring:
  datasource:
    url: ${AUTH_SERVICE_CONN_STRING:jdbc:postgresql://localhost:5432/${spring.application.name}}
    username: ${AUTH_SERVICE_DB_USER:${spring.application.name}}
    password: ${AUTH_SERVICE_DB_PASSWORD:${spring.application.name}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  data:
    #    mongodb:
    #      uri: ${MONGODB_CONN_STRING:mongodb://localhost:27017/${spring.application.name}}
    #      database: ${MONGODB_DB_NAME:${spring.application.name}}
    #      username: ${MONGODB_DB_USER:${spring.application.name}}
    #      password: ${MONGODB_DB_PASSWORD:${spring.application.name}}
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:qrestor123}
      database: ${REDIS_DB:2}
      timeout: 10000
  threads:
    virtual:
      enabled: true
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        security: INFO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans