FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/orders-0.0.1-SNAPSHOT.jar /app/orders-0.0.1-SNAPSHOT.jar
EXPOSE 8103
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/orders-0.0.1-SNAPSHOT.jar"]




