FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/menu-0.0.1-SNAPSHOT.jar /app/menu-0.0.1-SNAPSHOT.jar
EXPOSE 8102
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/menu-0.0.1-SNAPSHOT.jar"]




