apiVersion: v1
kind: Secret
metadata:
  name: feedback-secret
  namespace: qrestor-namespace
type: Opaque
data:
  POSTGRES_USER: ZmVlZGJhY2s=
  POSTGRES_PASSWORD: ZmVlZGJhY2s=
  POSTGRES_DB: YZmVlZGJhY2s=