FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/sellpoint-0.0.1-SNAPSHOT.jar /app/sellpoint-0.0.1-SNAPSHOT.jar
EXPOSE 8106
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/sellpoint-0.0.1-SNAPSHOT.jar"]




