server:
  port: 8092
  servlet:
    context-path: /${spring.application.name}/api/v1
app:
  global-name: QRestor
spring:
  application:
    name: mailer
  kafka:

    admin:
      properties:
        bootstrap.servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
#        spring.kafka.consumer.auto-offset-reset: earliest
#        spring.kafka.consumer.enable-auto-commit: true
#        spring.kafka.consumer.auto-commit-interval: 1000
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
