apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr_resolver
  namespace: qrestor-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr_resolver
  template:
    metadata:
      labels:
        app: qr_resolver
    spec:
      containers:
        - name: qr_resolver
          image: motherdock/qrestor:qr_resolver
          imagePullPolicy: Always
          ports:
            - containerPort: 8105
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: SPRING_PROFILES_ACTIVE
              value: prod