apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenboard
  namespace: qrestor-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchenboard
  template:
    metadata:
      labels:
        app: kitchenboard
    spec:
      containers:
        - name: kitchenboard
          image: motherdock/qrestor:kitchenboard
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: SPRING_PROFILES_ACTIVE
              value: prod