FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/kitchenboard-0.0.1-SNAPSHOT.jar /app/kitchenboard-0.0.1-SNAPSHOT.jar
EXPOSE 8100
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/kitchenboard-0.0.1-SNAPSHOT.jar"]




