FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/exporter-0.0.1-SNAPSHOT.jar /app/exporter-0.0.1-SNAPSHOT.jar
EXPOSE 8098
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/exporter-0.0.1-SNAPSHOT.jar"]




