apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellpoint
  namespace: qrestor-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sellpoint
  template:
    metadata:
      labels:
        app: sellpoint
    spec:
      containers:
        - name: sellpoint
          image: motherdock/qrestor:sellpoint
          imagePullPolicy: Always
          ports:
            - containerPort: 8106
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: SPRING_PROFILES_ACTIVE
              value: prod