akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka_broker:9091"
  clients-defaults:
    consumer:
      properties:
        default.api.timeout.ms: 120000
akhg.security:
  basic-auth:
    - username: admin
      password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      groups:
        - admin
micronaut:
  security:
    enabled: true