version: '3.8'

#zipkin, grafana, prometheus, postgres, redis, mongodb, minio services
services:


networks:
  backend_net:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local