global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "qresolver-service"
    metrics_path: /api/v1/actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8090']