global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: minio
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoicXJlc3RvcjEyMyIsImV4cCI6NDg2NTM0NDM5OX0.S-gSjH1zlRLvZIAj-evkgHSUvsCCTLZMI-L7p_tKeZrUFDv12KT1hNv7KZz4LjKMqnByBeH_ukQFrVqKMvdNCA
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:9000']
  - job_name: 'postgres-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9308' ]

  - job_name: "redis-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9121' ]

  - job_name: "qresolver-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: "gateway-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8097' ]

  - job_name: "feedback-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8095' ]

  - job_name: "exporter-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8094' ]

  - job_name: "kitchenboard-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8093' ]

  - job_name: "mailer-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8092' ]

  - job_name: "menu-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8096' ]

  - job_name: "orders-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]

  - job_name: "restaurant-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8098' ]