apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentor
  namespace: qrestor-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentor
  template:
    metadata:
      labels:
        app: paymentor
    spec:
      containers:
        - name: paymentor
          image: motherdock/qrestor:paymentor
          imagePullPolicy: Always
          ports:
            - containerPort: 8104
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: SPRING_PROFILES_ACTIVE
              value: prod