apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: qrestor-namespace
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: management
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: minio