server:
  port: 8080

#Eureka discovery client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
#Spring cloud gateway configuration
spring:
  application:
    -name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: qr-code-resolving
          uri: lb://qresolver
          predicates:
            - Path=/qr/**, /qresolver/**
          filters:
            - RewritePath=/qresolver/(?<segment>.*), /${segment}
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant/**
          filters:
            - RewritePath=/restaurant/(?<segment>.*), /${segment}
        - id: menu
          uri: lb://menu
          predicates:
            - Path=/menu/**
          filters:
            - RewritePath=/menu/(?<segment>.*), /${segment}
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}
        - id: feedback
          uri: lb://feedback
          predicates:
            - Path=/feedback/**
          filters:
            - RewritePath=/feedback/(?<segment>.*), /${segment}
        - id: importer
          uri: lb://importer
          predicates:
            - Path=/importer/**
          filters:
            - RewritePath=/importer/(?<segment>.*), /${segment}
        - id: auth
          uri: http://auth:8097
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /auth/api/v1/${segment}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    reactor:
      netty: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
