FROM bellsoft/liberica-openjre-alpine-musl:21.0.2-cds-aarch64
COPY ./target/mailer-0.0.1-SNAPSHOT.jar /app/mailer-0.0.1-SNAPSHOT.jar
EXPOSE 8101
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["java", "-jar", "/app/mailer-0.0.1-SNAPSHOT.jar"]




