app:
  domain: https://wanted-talented-peacock.ngrok-free.app
  auth:
    jwt:
      secret: ${AUTH_SERVICE_TOKEN_SECRET:qrestor_secret}
spring:
  datasource:
    url: ${AUTH_SERVICE_CONN_STRING:jdbc:postgresql://localhost:5432/${spring.application.name}}
    username: ${AUTH_SERVICE_DB_USER:${spring.application.name}}
    password: ${AUTH_SERVICE_DB_PASSWORD:${spring.application.name}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  threads:
    virtual:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        security: INFO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /feedback
      rate-limits:
        - bandwidths:
            - capacity: 3
              time: 1
              unit: minutes
              refill-speed: interval