name: Auth deployment to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: jarivs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        echo "Starting Maven build..."
        mvn -f backend/domain/auth/pom.xml clean package
        echo "Maven build completed."
      env:
        GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/domain/auth/dockerfile
        platforms: linux/arm64
        push: true
        tags: motherdock/qrestor:auth
